service: app2
hosts:
  - bsd.localdomain
doas: true
user: app2
strategy: jail
jail:
  ip_range: "10.0.0.0/24"
proxy:
  hostname: app2.local
  port: 3002
packages:
  - curl
  - libyaml
mise:
  ruby: 3.3.0
env:
  clear:
    - PORT: "3002"
    - RACK_ENV: production
  secret: []
before_start:
  - bundle config set --local path 'vendor/bundle'
  - bundle install
start:
  - bundle exec ruby app.rb
data_directories:
  - /var/bsdeploy/app2/storage: /app/storage
